name: CrowPi CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      ################################################################################
      # Build CrowPi image with Packer
      ################################################################################
      - name: Build CrowPi image with Packer
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: >-
          docker run
          --rm --privileged
          --workdir /github/workspace/image
          -v /dev:/dev
          -v /home/runner/work/_temp/_github_home:/github/home
          -v /home/runner/work/_temp/_github_workflow:/github/workflow
          -v "${{ github.workspace }}:/github/workspace"
          mkaczanowski/packer-builder-arm
          build crowpi.pkr.hcl

      ################################################################################
      # Create a GitHub release
      #################################################################################
      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          allowUpdates: ${{ github.ref == 'refs/tags/snapshot' }}
          prerelease: ${{ github.ref == 'refs/tags/snapshot' }}
          artifacts: >-
            image/crowpi.img.zip,
            image/crowpi.img.zip.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
