name: pi4j-os

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - crowpi
          - picade
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare build environment
        id: env
        run: |
          echo ::set-output name=RELEASE_VERSION::$(echo "${GITHUB_REF#refs/*/}" | sed 's/\//-/g' | tr -cd '[:alnum:]-')

      - name: Build OS image with Packer
        id: build
        if: >-
          (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/feat/image-flavors'))
          ||
          (github.event_name == 'pull_request')
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
        run: >-
          docker run
          --rm --privileged
          --workdir /github/workspace
          -v /dev:/dev
          -v /home/runner/work/_temp/_github_home:/github/home
          -v /home/runner/work/_temp/_github_workflow:/github/workflow
          -v "${WORKSPACE_PATH}:/github/workspace"
          mkaczanowski/packer-builder-arm
          build "${{ matrix.flavor }}.pkr.hcl"

      - name: Upload OS image as build artifact
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.flavor }}-image
          path: ${{ matrix.flavor }}.img.zip

      - name: Publish OS image to external repository
        if: >-
          github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        env:
          SFTP_SERVER: ${{ secrets.REPO_SFTP_SERVER }}
          SFTP_USERNAME: ${{ secrets.REPO_SFTP_USERNAME }}
          SSHPASS: ${{ secrets.REPO_SFTP_PASSWORD }}
          RELEASE_VERSION: ${{ steps.env.outputs.RELEASE_VERSION }}
        run: |
          sshpass -e sftp -oBatchMode=no -oStrictHostKeyChecking=no -b - "${SFTP_USERNAME}@${SFTP_SERVER}" << EOS
          put "${{ matrix.flavor }}.img.zip" "${{ matrix.flavor }}-${RELEASE_VERSION}.img.zip"
          put "${{ matrix.flavor }}.img.sha256" "${{ matrix.flavor }}-${RELEASE_VERSION}.img.sha256"
          EOS
