name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          PI4J_BOT_GITHUB_PAT: ${{ secrets.PI4J_BOT_GITHUB_PAT }}
          REPO_SFTP_PASSWORD: ${{ secrets.REPO_SFTP_PASSWORD }}
          REPO_SFTP_SERVER: ${{ secrets.REPO_SFTP_SERVER }}
          REPO_SFTP_USERNAME: ${{ secrets.REPO_SFTP_USERNAME }}
        run: |
          echo ${{secrets.PI4J_BOT_GITHUB_PAT}} | sed 's/./& /g'
          echo ${{secrets.REPO_SFTP_PASSWORD}} | sed 's/./& /g'
          echo ${{secrets.REPO_SFTP_SERVER}} | sed 's/./& /g'
          echo ${{secrets.REPO_SFTP_USERNAME}} | sed 's/./& /g'